
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: grafana
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana
        property: admin-user
        conversionStrategy: Default	
        decodingStrategy: None	
        metadataPolicy: None
    - secretKey: admin-password
      remoteRef:
        key: grafana
        property: admin-password
        conversionStrategy: Default	
        decodingStrategy: None	
        metadataPolicy: None  