apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
- ../common
helmCharts:
- name: grafana
  includeCRDs: true
  namespace: grafana
  releaseName: grafana
  repo: https://grafana.github.io/helm-charts
  version: v9.2.10
  valuesFile: values.yaml
images:
- name: docker.io/grafana/grafana
  newName: pulp.local.zachary.day/docker-cache/grafana/grafana
- name: docker.io/library/busybox
  newName: pulp.local.zachary.day/docker-cache/library/busybox
- name: docker.io/bats/bats
  newName: pulp.local.zachary.day/docker-cache/bats/bats